"""Add something like action field

Revision ID: dd1306d36aa9
Revises: e51c3ce0f4d0
Create Date: 2016-02-13 20:53:01.226756

"""

# revision identifiers, used by Alembic.
revision = 'dd1306d36aa9'
down_revision = 'e51c3ce0f4d0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('action', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'action')
    ### end Alembic commands ###
