"""Add ServerUser model

Revision ID: e51c3ce0f4d0
Revises: 22201e30816b
Create Date: 2016-02-07 22:40:43.218172

"""

# revision identifiers, used by Alembic.
revision = 'e51c3ce0f4d0'
down_revision = '22201e30816b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'kills')
    op.drop_column('user', 'deaths')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deaths', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('kills', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('server_user')
    ### end Alembic commands ###
